#!/usr/bin/env bash
# Regenerate the Homebrew formula in the ankit373/homebrew-hydra tap from a
# published release's archives + checksums, then commit & push it.
#
#   scripts/update-tap-formula.sh v1.0.0
#
# Requires: gh (authenticated with push access to the tap repo), curl.
# No HOMEBREW_TAP_GITHUB_TOKEN needed — uses your gh credentials.
set -euo pipefail

TAG="${1:?usage: update-tap-formula.sh vX.Y.Z}"
VER="${TAG#v}"
REPO="ankit373/hydra"
TAP="ankit373/homebrew-hydra"
BASE="https://github.com/${REPO}/releases/download/${TAG}"
PROJECT="hydra"   # archive filename prefix (goreleaser project_name)

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "→ Fetching checksums for ${TAG}…"
curl -fsSL "${BASE}/checksums.txt" -o "$work/checksums.txt"

sha_for() { grep " ${PROJECT}_${VER}_$1.tar.gz\$" "$work/checksums.txt" | awk '{print $1}'; }

DA="$(sha_for darwin_arm64)"; DI="$(sha_for darwin_amd64)"
LA="$(sha_for linux_arm64)";  LI="$(sha_for linux_amd64)"
for v in DA DI LA LI; do
  [ -n "${!v}" ] || { echo "✗ missing checksum ($v) in checksums.txt" >&2; exit 1; }
done

echo "→ Cloning tap ${TAP}…"
gh repo clone "$TAP" "$work/tap" -- --depth 1 >/dev/null 2>&1
mkdir -p "$work/tap/Formula"

cat > "$work/tap/Formula/hyctl.rb" <<RUBY
# Generated by scripts/update-tap-formula.sh — do not edit by hand.
class Hyctl < Formula
  desc "Multi-model AI orchestration — one Cortex, many Heads"
  homepage "https://hydra.uvansa.com"
  version "${VER}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/${PROJECT}_${VER}_darwin_arm64.tar.gz"
      sha256 "${DA}"
    end
    on_intel do
      url "${BASE}/${PROJECT}_${VER}_darwin_amd64.tar.gz"
      sha256 "${DI}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/${PROJECT}_${VER}_linux_arm64.tar.gz"
      sha256 "${LA}"
    end
    on_intel do
      url "${BASE}/${PROJECT}_${VER}_linux_amd64.tar.gz"
      sha256 "${LI}"
    end
  end

  def install
    bin.install "hyctl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hyctl version")
  end
end
RUBY

echo "→ Committing & pushing formula…"
git -C "$work/tap" add Formula/hyctl.rb
git -C "$work/tap" -c user.name="hydra-release" -c user.email="release@uvansa.com" \
  commit -m "chore: hyctl ${TAG}" >/dev/null
git -C "$work/tap" push origin HEAD >/dev/null

echo "✓ Tap updated: brew tap ankit373/hydra && brew install hyctl   (→ ${TAG})"
